### ISSUE TITLE
Error loading Anand Vihar location

### ISSUE THREAD

**Issue by smit1678** [openaq/openaq.org#112]
Flagging an error loading the Anand Vihar location. Route to get here -- panned around on the map to India, https://openaq.org/#/map, then clicked View More on the Anand Vihar location near Delhi: `https://openaq.org/#/location/Anand Vihar?_k=2xeq0n`

Console errors of: 

```
TypeError: Cannot read property 'sourceURL' of undefined
```

![openaq 2016-09-02 15-41-25](https://cloud.githubusercontent.com/assets/796838/18207607/bd13ec70-7123-11e6-9332-eb21148cb53f.png)

Seen on Version 52.0.2743.116 (64-bit) OSX 10.11.4

cc @danielfdsilva @jflasher

**Comment by jflasher** [comment]
This could be coming from the fact that Anand Vihar first came from one source (no longer used) and now comes from another source. It's original source wouldn't be in the `/source` API returned data so maybe it's failing to match?

**Comment by danielfdsilva** [comment]
@jflasher yes, exactly that.
The sourceName for Anand Vihar is `Anand Vihar` (https://api.openaq.org/v1/locations?location=Anand%20Vihar) and that source is not in the sources. Is this something you can fix?

**Comment by olafveerman** [comment]
Should this be resolved in a more structural way? Is there a way to properly 'retire' sources?
This may happen in the future when we decide to switch the Dutch data for the EU source.

**Comment by jflasher** [comment]
@olafveerman yeah, that's what I'm wondering. Even if we do that, we'll have the issue where Anand Vihar data may be showing wrong source (if there are multiple and we're only showing on)? The latest Anand Vihar data should be coming from CPCB, not Anand Vihar I think.

**Comment by jflasher** [comment]
@danielfdsilva @olafveerman would like to raise this again as it'll definitely come up during Delhi workshop. I think there are three things

1. How we should handle old sources?
I guess we should keep them around in `/sources` and maybe just have a flag like `active: false` or similar.

2. What do we do in the API?
I think for `/locations`, `sourceName` becomes an array that has every source that was used for that location. In the case above for Anand Vihar, it'd be `["CPCB", "Anand Vihar"]`. Each individual measurement only has one source, and that's already properly reflected in API return.

3. What do we show on website?
If a location has multiple sources, I think we just list them both whenever they're listed.

**Comment by danielfdsilva** [comment]
@jflasher Does a location use multiple sources at the same time, or only one is active and the other ones are retired?

Listing multiple sources on the location page is fine, but when it comes to modals, listing multiple can get tricky...

**Comment by jflasher** [comment]
Currently (and I think always) a single location would only use 1 source at a time.

**Comment by danielfdsilva** [comment]
So could we just use the "active" source and show that one?

**Comment by jflasher** [comment]
I guess that’s more correct, but I think that’s potentially misleading since they could be seeing data from another source. 


On November 4, 2016 at 2:11:29 PM, Daniel da Silva (notifications@github.com) wrote:

So could we just use the "active" source and show that one?

**Comment by jflasher** [comment]
But in practice, might not actually be that big of a deal.


On November 4, 2016 at 2:13:07 PM, Joe Flasher (flasher@openaq.org) wrote:

I guess that’s more correct, but I think that’s potentially misleading since they could be seeing data from another source. 


On November 4, 2016 at 2:11:29 PM, Daniel da Silva (notifications@github.com) wrote:

So could we just use the "active" source and show that one?

**Comment by jflasher** [comment]
Fixed this by using active source in `sourceName`. Will open new issue to show all sources on these location pages.
