### ISSUE TITLE
Listing sourceType + source url for filtering and on location cards

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq.org#113]
In recent conversations with folks, it was suggested multiple times to make the `sourceType` and `attribution` url clearer to users, as well as to make sure it is clear the official data, since captured in real-time, are not necessarily QA/QC'ed.

To do that, I'm thinking:

(0) Alter copy on location and country pages to reflect the QA/QC comment, as well as put stronger/clearer language on the front page about the data origins (I'm doing this now)
1. Add in `sourceType` to the filter choices: 
   ![screen shot 2016-09-07 at 10 53 01 pm](https://cloud.githubusercontent.com/assets/13404290/18328226/42479f9e-754e-11e6-89b8-4f15e00a97f9.png)
2. Add `sourceType` to the location cards. 
   ![screen shot 2016-09-07 at 10 53 23 pm](https://cloud.githubusercontent.com/assets/13404290/18328289/775ff1e0-754e-11e6-8777-b90f898ba9e8.png)
3. Add `sourceType` to the map cards when a location is selected, as well as the `attribution` url.
4. (which I'm more iffy about): Add in `sourceType` to the csv file, but it seems like this will make the files larger than necessary and it will already link to the originating source url. @jflasher, is that right (or have any other thoughts)?

**Comment by jflasher** [comment]
Source and type are now prominently displayed on cards, closing.
