### ISSUE TITLE
Comparing gas phase pollutants with different units

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq.org#118]
Notice that we are showing comparisons between places with ozone measured originally in two different forms (e.g. units of ppm and ug/m^3). I assume we're doing this the same way as the map. We probably can't really do a one-on-one comparison so well, due to blanket, global assumptions we're making in pressure and temperature that we did for the global map comparison. We can consider keep this (it's NICE to be able to compare different places), but if so, we'll need to add some messaging to qualify what we're doing, since a one-on-one comparison is rather sensitive to the T and P we pick to convert the values.

**Comment by jflasher** [comment]
These are actually two different variables now so are not compared next to each other, closing.
