### ISSUE TITLE
Feedback on New Platform: Anonymous National-Level Air Quality Monitoring Staff

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq.org#119]
From a conversation with a national level air quality agency staff member who is responsible for multiple instruments' maintenance and data reporting.

**Substantive:**
- add disclaimer about real-time data being typically non-QA/QC'ed
- Very interested in seeing meta data included or a way to channel to a person associated with a given source questions on the meta data. We discussed perhaps a meta data wiki?
- Thought perhaps putting source attribution on map card might be a good idea. 

**Visual:**
- This person liked this visual from UNEPLive where our data are displayed better than our map because the dots were bigger and it was easier to tell pollution levels at a glance:
  ![screen shot 2016-09-12 at 10 42 10 am](https://cloud.githubusercontent.com/assets/13404290/18429784/9b335442-78d5-11e6-9a00-8844cae31b89.png)
- They didn't immediately recognize they could toggle parameter types on the map.

**Building off of the Platform:**
- This person was interested in a statistical analysis of real-time data with the QA/Qc'ed data for various locations
- This person was very interested in an alert system that would let them know when one of their instruments was down. This person currently gets alerts in multiple ways based on different instrumentation software. Also, these instrument model-specific alerts do not catch things like repeating non-zero values. This person just has to go and notice such things themselves. 
- This person was worried about an app that automatically pulled data because it might not be designed to catch such errors.

**Comment by olafveerman** [comment]
That's some pretty solid feedback.

What is the kind of meta-data that would be interesting? This is at source level?
When building an adapter, we are collecting a lot of notes about each source that are not exposed through the API. Things like assumptions, methodology, and so on. Currently they're scattered in the Github issues and Pull Requests, but I could imagine we find a way to capture them and show them on the platform.

**Comment by RocketD0g** [comment]
Yup, at the source level, this person (and this has come up in other conversations too) are interested in understanding the instrument type, calibration/maintenance procedures, and location setting (e.g urban, rural, industrial, etc.). 

That's cool on capturing such data already - I don't have the best feel for how systematically it is shared and wonder how to do that - and also wonder how to keep it up to date over time. Perhaps a wiki for people to fill out? Not sure.

**Comment by RocketD0g** [comment]
Note: Disclaimer about real-time data being typically non-QA/QC'ed has been added to various portions of the site.
