### ISSUE TITLE
Map coloring and point size 

### ISSUE THREAD

**Issue by ascalamogna** [openaq/openaq.org#139]
We got a few comments on the current map colors not being bright enough and large enough, and preferences for the old map color scheme where expressed, where it was clearer where hot spots/cold spots were.

I personally have a strong preference for the old color scheme, or one similar to it, and to make the points larger and more distinct. I think it is very important to see as soon as you look at the map on a global level which places a) have any data, and b) have high versus low levels of pollution. One external factor with the coloring: while we are not using any particular AQI scale purposely, nearly all scales for pollutants - for better or worse - well-constructed or otherwise - use a red to blue/purple scale. People who look at air pollution maps are just used to seeing that and other significantly differing schemes can look jarring.

**Comment by DylanMoriarty** [comment]
Ok. So, going back to a color scheme that's closer to the original...

*For these screenshots I bumped up the overall radius of each point a pixel for the low zoom levels.

1.
<img width="1157" alt="screenshot 2016-11-04 13 34 17" src="https://cloud.githubusercontent.com/assets/9341928/20016171/ce8bccaa-a294-11e6-93b5-483142637d68.png">

2. ( Old colors )
<img width="1115" alt="screenshot 2016-11-04 13 51 05" src="https://cloud.githubusercontent.com/assets/9341928/20016413/c1dd348e-a295-11e6-90ae-7837278f286e.png">

3. ( Tweaked older colors )
<img width="1119" alt="screenshot 2016-11-04 14 03 25" src="https://cloud.githubusercontent.com/assets/9341928/20016820/7eb7485a-a297-11e6-8cd1-cc439d07bed1.png">

4. ( No red )
<img width="1023" alt="screenshot 2016-11-04 14 12 53" src="https://cloud.githubusercontent.com/assets/9341928/20017171/d4a972be-a298-11e6-9036-8aeb4335340c.png">

For me, I dig 1# & 3#, and feel like the first does the better job of not making it look like there's a middle value or turning point for the AQ values. I know we'd discussed not using red for the areas with the most pollutants, so maybe a happy medium would be just dulling them a bit more.

@ascalamogna

**Comment by ascalamogna** [comment]
@DylanMoriarty I like 1 and 3 as well. What do you think @olafveerman?

**Comment by olafveerman** [comment]
I like 3 the most. What 'throws' me off on 1, is that the stronger green has a higher value than the blue. Instinctively, if I look at the map, I think that the green dots are the lower values.

@DylanMoriarty

**Comment by olafveerman** [comment]
What do you think @RocketD0g and @jflasher ?

**Comment by RocketD0g** [comment]
I like 1 and 3, but after reading @olafveerman's comment on 1, I can't unsee what he's saying! So I like 3 the most. @jflasher?

**Comment by jflasher** [comment]
3 ftw!

**Comment by DylanMoriarty** [comment]
👍

**Comment by olafveerman** [comment]
Adressed here: https://github.com/openaq/openaq.org/pull/150
