### ISSUE TITLE
Map disappears after load

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq.org#149]
This happens to me on Chrome but does not happen to Christa on Chrome. Happens for me on both prod and staging.

1. Load main page https://openaq-staging.org
2. Somewhat quickly go to Map
3. Hover over nav bar (Home - Data - Map etc) 

Map will disappear. Moving the map at all causes it to reappear. Can someone else check if this is happening to them?

**Comment by olafveerman** [comment]
We weren't able to reproduce this on a couple of different os/browser combinations. Do you still see the same behavior?

**Comment by jflasher** [comment]
I do, but I'm fine closing this and seeing if it gets raised anywhere else.
