### ISSUE TITLE
Error on Norway country page

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq.org#159]
https://openaq.org/#/countries/NO has error

`Uncaught (in promise) Error: At least center or bbox has to be provided to MapComponent(…)`

Not sure if it's due to data or something else?

**Comment by dolugen** [comment]
Bounding box for Norway is missing in `app/assets/scripts/utils/countries.js`.

**Comment by jflasher** [comment]
@danielfdsilva What's the best way to get the bbox?

**Comment by danielfdsilva** [comment]
@jflasher There's not really a preferred way. As long as the order of the coordinates is correct, you can get them from anywhere
