### ISSUE TITLE
JS error when accessing shared compare

### ISSUE THREAD

**Issue by dolugen** [openaq/openaq.org#162]
The page loads forever without any error message, unless you look into the JS console.

The error is:
```
TypeError: o is null
```

The link is:

https://openaq.org/#/compare/Beijing%20US%20Embassy/MNB/FRANCONIA?parameter=pm25&_k=iy9n92

Without the _k parameter, the page works (a new _k value is generated on load).

**Comment by jflasher** [comment]
@dolugen can you check this out and see if it's still an issue? My guess is that it was coming from a failed load (or a error object being cached and served). We've been having some intermittent API issues with the servers coming up and down at times.

**Comment by dolugen** [comment]
It works!
