### ISSUE TITLE
Somehow indicate data present for locations for different parameters

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq.org#167]
It hurts me that we have a lot of data for pm10 or o3 that doesn't appear at all on map for pm25 (default). I'm thinking something like small grayish dots just to give some texture, similar to how we handle old data now?

**Comment by jackkoppa** [comment]
Hey all. Happy to join, and want to get started on contributing here. This seems like a good place for me to start, so I'll assign to myself for now. Hoping to get started in about 2 weeks (after relocating)

**Comment by jflasher** [comment]
Thanks @jackkoppa !

**Comment by jflasher** [comment]
Closing this due to age, but can be reopened if community continues to raise as an issue.
