### ISSUE TITLE
Parameter selection not working on Data download page

### ISSUE THREAD

**Issue by dolugen** [openaq/openaq.org#176]
Page address: https://openaq.org/#/locations?countries=MN&_k=vcp7kk

You click on a download button related to a location. You're taken to a modal window.

When you click on parameter checkboxes, the box is not checked, but the URL is updated with the parameter. The downloaded CSV doesn't contain filtered results, it contains all parameters.

**Comment by jflasher** [comment]
@dolugen what browser are you using? This worked fine for me in the latest version of Chrome. Could you check your console when clicking the boxes to see what requests are being made? I noticed that when I click on a parameter, it's making a request to the API to see what the total  results are. Maybe this request is timing out and throwing things off?

**Comment by dolugen** [comment]
OS: Ubuntu 16.04.2
Tested browsers: Firefox 51.0.1 (64-bit), 56.0.2924.87 (64-bit)

When checked, it's sending requests to locations endpoint with selected parameters. Example: https://api.openaq.org/v1/locations?page=1&limit=15&country%5B0%5D=MN&parameter%5B0%5D=no2&parameter%5B1%5D=so2

There's no timeout.

**Comment by dhhagan** [comment]
I'm using chrome59 and the parameter selection doesn't work for me either. It alters the uri, but doesn't actually change states in terms of indication of the checkbox.

**Comment by jflasher** [comment]
No longer seems to be an issue, closing.
