### ISSUE TITLE
Ahmedabad (India) station not updating

### ISSUE THREAD

**Issue by urbanemissions** [openaq/openaq.org#199]
https://api.openaq.org/v1/measurements?city=Ahmedabad&parameter=pm25&date_from=2017-04-09&date_to=2017-04-10&format=csv

This shows a blank file

Same for the rest of the days this month.

http://www.cpcb.gov.in/CAAQM/frmCurrentDataNew.aspx?StationName=Maninagar&StateId=8&CityId=337

**Comment by dolugen** [comment]
Hey @urbanemissions, this looks like a data source problem. The Maninagar station was last updated in March 2017, as you can see in [this OpenAQ response](https://api.openaq.org/v1/locations?city=Ahmedabad), and also the cpcb link above.
