### ISSUE TITLE
Special characters incorrectly encoded

### ISSUE THREAD

**Issue by mhamberg1** [openaq/openaq.org#200]
Many of the locations containing special characters or an accent mark are rendered incorrectly when I pull down the feed.

Is this fixable?

![image](https://cloud.githubusercontent.com/assets/26781730/25278841/89d6332c-2672-11e7-9c66-f4fc9e586568.png)

**Comment by jflasher** [comment]
Last time I looked, the EEA feed wasn't providing UTF-8 which is most likely leading to some of these issues. It could be coming from our adapters, but in a lot of cases, it's coming from the source which is not something I'd want to fix.  

Can you provide sourceName alongside the locations to make it easier to track down? Thanks!

**Comment by mhamberg1** [comment]
Yeah EEA is the main culprit but there are also a few coming from AirNow. Here's a list:

[OpenAQ - encoding_issues.txt](https://github.com/openaq/openaq.org/files/947205/OpenAQ.-.encoding_issues.txt)

**Comment by mhamberg1** [comment]
it's also useful to understand that out of 357 or so encoding issues we see, around 254 of those locations are actually **duplicates** in the data and their duplicate location actually has a clean name. So a partial fix for this issue which would also help with data cleanliness is to dedupe using name or lat/long and keep only the good name (and the most recent record).

**Comment by jflasher** [comment]
Closing this due to age, but can be reopened if community continues to raise as an issue.
