### ISSUE TITLE
Display date in a singular timezone on location page

### ISSUE THREAD

**Issue by dolugen** [openaq/openaq.org#211]
I was browsing a [Location page](https://openaq.org/#/location/Nisekh?_k=hscyve) and noticed that while most of the dates were in local time, the map was using the UTC time. Example shown below.

Couple of ideas:

* Use local time in the map data
* Indicate that dates are in local timezones, somewhere near the measurements data, as well as the plot

From "Latest measurements" section:
![screenshot from 2017-06-30 00-58-40](https://user-images.githubusercontent.com/194381/27700427-23296f46-5d30-11e7-88a6-30a08f2164f6.png)

From the map section:
![screenshot from 2017-06-30 00-59-05](https://user-images.githubusercontent.com/194381/27700433-25c3ec68-5d30-11e7-9d98-21a7e6d54160.png)

**Comment by jflasher** [comment]
Closing this due to age, but can be reopened if community continues to raise as an issue.
