### ISSUE TITLE
Some locations are inaccessable

### ISSUE THREAD

**Issue by meiamsome** [openaq/openaq.org#216]
Related to openaq/openaq-api#327, the location URL only accepts a location name, causing combination of multiple locations.

Look at the graphs here for example: https://openaq.org/#/location/Portsmouth

I would suggest changing the URL path to `location/:country/:city/:name`, or similar, but that would result in a lot of dead links unless a page is added to redirect from older-style links. Also, this would cause issues with the compare page.

**Comment by jflasher** [comment]
Huh yeah, very interesting. cc'ing @danielfdsilva in case he has any great wisdom here.

**Comment by danielfdsilva** [comment]
Maybe the easiest solution is to add a slug to each location like `[country]-[city]-[name]`. That would allow us to maintain the same url structure and the compare page would work with minimal change.

We'd still need the redirects though.

**Comment by meiamsome** [comment]
That seems sensible, @danielfdsilva - although there are ~180 cities with the - character in their name and ~1300 locations, so I guess we'd just be making more locations inaccessible without a custom urlencoding method to fix that?

**Comment by danielfdsilva** [comment]
@meiamsome That wouldn't be a problem because we'd be precomputing the slug, and the search would use that. We could not do a split to get the different parts but I don't see that as a problem.

**Comment by meiamsome** [comment]
@danielfdsilva Oh, you mean actually add it to the database/equivalent? That would work, as long as there's no pairs of cities & names that are ambiguous... I would say that's unlikely, but frankly it's the sort of thing I'd expect!

**Comment by danielfdsilva** [comment]
@meiamsome Yup, exactly what I meant. :)
I doubt that there are matching pairs of country city location, but it just a matter of checking and adding a `-2` to the repetition

**Comment by jflasher** [comment]
Looks like the platform is now using the unique ids for the location names which should mean this is no longer an issue, closing.
