### ISSUE TITLE
Location page map wording is potentially misleading

### ISSUE THREAD

**Issue by meiamsome** [openaq/openaq.org#217]
Currently the wording is:
`There are {x} other locations in {city}, {country}`
This is from when the query for the map was done by the city of the current sensor. However, it is currently done by a radial search, so perhaps wording of something along the lines of
`There are {x} other locations within 10km of {location}, {city}, {country}`
would be better? I can think of some occurrences, however, where this could get very long, having all three names there.

**Comment by dolugen** [comment]
How about this:

`There are {x} other locations nearby in {city}, {country}`

**Comment by jflasher** [comment]
Believe this is not an issue with current UI, closing.
