### ISSUE TITLE
Re-design of Community Page

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq.org#226]
We're getting lots of examples of usage of the OpenAQ platform and/or collaborations among the community (yay!), but it looks a little cluttered on the Community page. 

When we're able, we'll want to re-think a re-design of communicating both the specific works, as well as the general themes of the work (e.g. science, policy, open-source tool, journalism, partnerships). 

https://openaq.org/#/community

Maybe a world map, color coded by theme, clickable for more info and with a list of all projects underneath the map?

If anyone has thoughts or good examples, would love to hear them.

**Comment by jflasher** [comment]
Closing this due to age, but can be reopened if community continues to raise as an issue.
