### ISSUE TITLE
Historical data has gone

### ISSUE THREAD

**Issue by JHvdZ** [openaq/openaq.org#238]
Since last week it seems impossible to retrieve historical data which were accessible before; e.g. the PM2.5 data for The Hague for 2016 are not available anymore (only data from August 2017 and later seems available now). Is there a change in data availability policy?

**Comment by jflasher** [comment]
Hi @JHvdZ, this is discussed over in https://github.com/openaq/openaq-fetch/issues/416 and yep, you're right that the API currently only provides 90 day rolling access now, though all the data is still available. Going to open an issue to make that clearer on the download box. Also closing this so we keep any discussion in one place.
