### ISSUE TITLE
Map does not work on latest Chrome.

### ISSUE THREAD

**Issue by AreteY** [openaq/openaq.org#261]
Requires another browser like Safari. Similar problem with OpenAQ browser too. Will cross-post there.

**Comment by jflasher** [comment]
Hi @AreteY, thank for opening this. Can you provide more details when you say the map doesn't work? Does it look like this https://github.com/openaq/openaq.org/issues/149 ?

**Comment by AreteY** [comment]
Sure! Actually the map doesn't load at all (blank map, all white) on my Chrome browser, Version 66.0.3359.170 (Official Build) (64-bit), whereas it loads on Safari. What does load is the header bar (Home-Data-Map-Community-etc.) and the map legend.

The other page that is affected is "Browse by Country." The home page for "Browse by Country" loads, but if you click on any specific country, you get: a blank white map with legend (so no map) and the locations listed doesn't necessarily correspond with the country you clicked on (maybe storing last click?). If I reload the country page, then the correct countries load with a blank map.

I did clear my browsing data on my Chrome browser. Also my Safari browser is fine, Version 11.1 (12605.1.33.1.4); no problems with the map or browse by country.

**Comment by jflasher** [comment]
Once you load and it’s blank, can you grab the map and move it with the mouse and see if it pops back in?

**Comment by AreteY** [comment]
No, if I try to grab the map, nothing happens. Still blank screen.

**Comment by AreteY** [comment]
Hi @jflasher- My webGL has been disabled for chrome. I believe this is likely the reason. Thanks. I'll also contact the community member who reported it on the community survey as well. Closing this PR!
