### ISSUE TITLE
Add in more detailed source attribution on Data Cards

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq.org#262]
We have received a request to include more attribution details on our website. 

For instance, this station location in Carrot Creek Alberta shows up [like this](https://openaq.org/#/location/Carrot%20Creek?_k=ftim27): 

![screen shot 2018-06-23 at 12 21 04 pm](https://user-images.githubusercontent.com/13404290/41811563-05b1be26-76e0-11e8-8156-8d1123ad959e.png)

Yet [the full attribution available via our API](https://api.openaq.org/v1/measurements?location=Carrot%20Creek&include_fields=attribution&limit=1) includes linking to not only the US EPA's AirNow system, but also to Alberta Environmental Monitoring and Reporting Agency (AEMERA): 
![screen shot 2018-06-23 at 12 20 50 pm](https://user-images.githubusercontent.com/13404290/41811573-30ef9978-76e0-11e8-9365-50ca4a52ef91.png)

The idea would be to alter the Data Location card to include the second-level of source attribution.

**Comment by CamLatimer** [comment]
Hi. I'm down to work on this.  Are you all using 'Develop' to checkout new branches and submit pull requests to?

**Comment by jflasher** [comment]
Hey @CamLatimer that'd be great and yep `develop` is the base. To make it easier to develop and see all the sources, I'd recommend just pointing at the production API. You may need to run the site once via `npm run serve` but it should create a local config file and then you can just point it to the production API like in https://github.com/openaq/openaq.org/blob/develop/app/assets/scripts/config/production.js#L13

**Comment by jflasher** [comment]
Closed with https://github.com/openaq/openaq.org/pull/268
