### ISSUE TITLE
Issues with map 

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq.org#263]
In chrome, I can no longer get the map to load. Also, users have reported that when they get the map to load, they cannot click on a city to get the card to come up (regardless of browser and I have seen this first hand in Safari). 

EDIT: @jflasher I can't imagine this has anything to do with the recent backend changes, but tagging you just in case.

**Comment by jflasher** [comment]
Some of this is fixed with update to mapbox-gl but there is still some wonkiness.

**Comment by jflasher** [comment]
Believe these issues are cleared up now with #266. If other issues appear, we can track with new issues.
