### ISSUE TITLE
Issues with Data/Map

### ISSUE THREAD

**Issue by LSanders1** [openaq/openaq.org#269]
Selecting locations or countries under "data" produces TypeError: a[o].flat is not a function

**Comment by jflasher** [comment]
This may be related to https://github.com/openaq/openaq.org/pull/264/files but I don't see the same behavior.

@LSanders1 can you let me know what browser (name and version) you're using?  And you're just going to the landing page and trying to navigate to the either of those tabs and see the error?

**Comment by jflasher** [comment]
This should now be fixed. You may need to do a hard refresh or wait for caching to expire, but I confirmed it was an issue, merged https://github.com/openaq/openaq-fetch/pull/546 and confirmed it now works. Feel free to reopen if you're still seen the same issue. Thanks!
