### ISSUE TITLE
Use "order_by=distance" instead of "nearest" on locations queries

### ISSUE THREAD

**Issue by vgeorge** [openaq/openaq.org#286]
The "nearest" parameter is [deprecated](https://github.com/openaq/openaq-api/blob/develop/api/routes/locations.js#L18) and will be unsupported by data API soon. The web client should use "order_by=distance", which has the same effect.

**Comment by jflasher** [comment]
@vgeorge I just tried to update this to match the API functionality, but I am  getting 0 results when using the below query, which I think should work? I checked the `locations` table on staging and it does have records, including ones right nearby. 

https://api.openaq-staging.org/v1/locations?order_by=distance&limit=3&coordinates=38.9890349,-76.5104805

**Comment by jflasher** [comment]
Should be resolved with https://github.com/openaq/openaq.org/pull/287

**Comment by vgeorge** [comment]
Just a clarification, the query above didn't return any results because there were no locations within the default radius of 2500 m. If the radius was increased to 20 km the query would return some nearby locations:

https://api.openaq-staging.org/v1/locations?order_by=distance&limit=3&coordinates=38.9890349,-76.5104805&radius=20000
