### ISSUE TITLE
Review Testimonials

### ISSUE THREAD

**Issue by olafveerman** [openaq/openaq.org#292]
The testimonials provided in the Google Doc were added to the redesign branch. There are still some todos:

* [x] review of short quotes
The quotes are all fairly long. To fit the design, they need to be shortened significantly. I've made an attempt to capture the most interesting message. Please review and suggest changes: https://github.com/openaq/openaq.org/blob/feature/openaq-redesign/app/assets/content/testimonials.json
* [x] add Climateworks quote  
In the doc this is listed as 'coming soon'. Is this still the case?
* [x] add a square and higher quality image for Climateworks. Testimonials are expected to be headshots
* [x] add image Medellin  
* [x] add image for Karin Tuxen-Bettman

**Comment by olafveerman** [comment]
Thanks for the review @RocketD0g 
Keeping this open until the last issue are fixed.

**Comment by RocketD0g** [comment]
Just got an updated logo from SIATA for their quote with higher quality. Here are png and jpg versions:

![siata](https://user-images.githubusercontent.com/13404290/63363448-9d3fb780-c341-11e9-9f23-aa9c48655791.jpg)

![siata](https://user-images.githubusercontent.com/13404290/63363457-a03aa800-c341-11e9-973b-89efd0861b59.png)

**Comment by RocketD0g** [comment]
Here is Karin's headshot:

![Karin-Tuxen-Bettman](https://user-images.githubusercontent.com/13404290/64056089-c55bc180-cb5e-11e9-9d68-b4fb982c6d64.jpg)

**Comment by olafveerman** [comment]
Thanks, added.

Closing this issue.
