### ISSUE TITLE
Missing content community impact

### ISSUE THREAD

**Issue by olafveerman** [openaq/openaq.org#293]
On the new community project page, we need the following content for each entry:

- logo
- location
- type of project (eg. `data platform`)

The current design does not support links in the project description. The full card is linkable already, and we can't have a link inside a link.

**Comment by AreteY** [comment]
I will start populating this community content here: https://docs.google.com/document/d/185KnR1AZCLli47a9UOCEsoMz63NKR2ISZOoKkQtdWsA/edit?usp=sharing

**Comment by RocketD0g** [comment]
- Logos are available [here](https://github.com/openaq/openaq.org/tree/develop/app/content/projects) via link, or [here](https://github.com/openaq/openaq.org/tree/develop/app/assets/graphics/content/projects) in this directory, unnumbered. Not quite sure what is the most seamless way to give these to you, so let me know if this doesn't suit. For instance, I can link them in the table below.

- Retaining the same number as in the link [here](https://github.com/openaq/openaq.org/tree/develop/app/content/projects) in the table below(obviously, not yet filled out, haven't reconciled this with @AreteY's linked file in this [comment](https://github.com/openaq/openaq.org/issues/293#issuecomment-519757480)). Suggest we define "Location" as the geographic application of the tool/project (e.g. "Smokey" might have been created in Delhi India, but it is usable globally), when possible, or the location of the person/group producing the work, when unclear on geographic scope of application.

WIP

| Project #  |      Location     | Project Type |
|----------|:-------------:|------:|
| 1| Global   | TBF | 
| 2 |    centered   |   TBF|
| 3 | right-aligned |    TBF |
| 4 | right-aligned |    TBF |
| 5 | right-aligned |    TBF |
| 6 | right-aligned |    TBF|
| 7 | right-aligned |    TBF |
| 8 | right-aligned |    TBF |
| 9 | right-aligned |    TBF |
| 10 | right-aligned |    TBF |
| 11 | right-aligned |    TBF |
| 12 | right-aligned |    TBF|
| 13 | right-aligned |    TBF |
| 14 | right-aligned |    TBF|
| 15 | right-aligned |  TBF |
| 16 | right-aligned |   TBF|
| 17 | right-aligned |    TBF |
|18 | right-aligned |    TBF |
| 19 | right-aligned |    TBF |
| 20 | right-aligned |    TBF |
| 21 | right-aligned |    TBF |
| 22 | right-aligned |    TBF |
| 23 | right-aligned |    TBF |
| 24 | right-aligned |    TBF |
| 25 | right-aligned |    TBF |
| 26 | right-aligned |   TBF |

**Comment by olafveerman** [comment]
Did some work on the community cards:

- added location and project types to each of them. When I had no idea what to tag them as, I added them to a placeholder category: 'TBD'. @RocketD0g @AreteY please review.
- I tried to get as many logos as possible. The older card images are not used anymore, only the logo on the bottom right
- I added a category 'Developer Tools'
- should we completely remove 'Hawa Badlo'. The link leads to a 'coming soon' page

**Comment by AreteY** [comment]
Hi All- reviewed #307 ; in response, updated Google Doc from above with changes and added project types/location where needed.

- Category types 'Developer Tools' and 'Software' (instead of App/Software) are good.
- UB Post link is also missing. Maybe leave in case it comes back?
- Can we update WIFIRE logo? I'll try to upload to GH, new logo also in Google Doc if ready to update.

**Comment by olafveerman** [comment]
Thanks for the review @AreteY 
Addressed your comments in the latest commit. Closing this issue.
