### ISSUE TITLE
Fix new icons on Chrome for Android

### ISSUE THREAD

**Issue by ricardoduplos** [openaq/openaq.org#294]

**Comment by olafveerman** [comment]
Also getting this on Chrome on Linux:
![image](https://user-images.githubusercontent.com/751330/63295084-d3c1f780-c299-11e9-9a72-daf248cb4f3b.png)

**Comment by ricardomestre** [comment]
@olafveerman Thanks for pointing this out. I'll work on a fix.

**Comment by jflasher** [comment]
Would be good if someone with mentioned OS above could see if this was still an issue.
