### ISSUE TITLE
Review inner links

### ISSUE THREAD

**Issue by ricardomestre** [openaq/openaq.org#298]
- [x] Header
- [x] Footer
- [x] Join a community fold
- [x] Workshops fold
- [x] Connect with the community fold

---

- [x] Homepage
- [x] Community
- About  
  - [x] Download 880 form

**Comment by olafveerman** [comment]
Flagging that 'Support our mission' and 'Participate' on the homepage and in the footer both lead to `/community`.

@RocketD0g what the best page to link to for 'support our mission'?

**Comment by RocketD0g** [comment]
Mmm. I don't recall precisely, but I think what would work is having it go to the "Sponsor" portion of the "About" page, where there is already a "become a sponsor" button. 

Alternatively, it could go straight to where the "become a sponsor" button goes, which is just an email to info@openaq.org.

**Comment by olafveerman** [comment]
Linked the button to info@openaq.org.

I believe I addressed all the remaining links. If there's still something missing, we can open another issue.
