### ISSUE TITLE
Email address when subscribing to newsletter

### ISSUE THREAD

**Issue by olafveerman** [openaq/openaq.org#304]
The 'subscribe to newsletter' feature asks people to provide their email.

![image](https://user-images.githubusercontent.com/751330/63289617-89d31480-c28d-11e9-975c-51536db5b828.png)

Clicking the button leads to an empty Mailchimp form, and requires the person to fill in the email again, which is redundant.

Two options:

1. remove the email field from the website, and lead straight to the empty Mailchimp form
2. keep the field on the website, but populate the email field on the Mailchimp form with the value provided

**Comment by Tokelin** [comment]
From what I see in the opened PR #343 option 2 is already implemented in there. However the last comment on the PR mentions that "It'd be great to have folks' first and last names too"

Considering there is only the singular input for an email, this would require adding more fields for people's names. In my opinion that would clutter the existing UI. Taking that into account this issue looks resolved, however the PR is just not merged.
