### ISSUE TITLE
Workshop content

### ISSUE THREAD

**Issue by olafveerman** [openaq/openaq.org#311]
Replace placeholder content on the workshops page with the real deal:
http://openaqv3.surge.sh/#/community/workshops

**Comment by RocketD0g** [comment]
- Header: OpenAQ Workshops
- Below Header: "We hold workshops to help people in various sectors find the most impactful ways they can fight air inequality in their local community." 
- If there's enough room in the before header section, also add: "[Contact us]( info@openaq.org), if you are interested in holding a workshop in your community!"

For the cards, I don’t know if we need an additional description besides date and location. I suggest the date be the small font and the location the big one.>

**Card Info**
(Don't know why the images look so small, but they seem okay once you click on them.)

| City, Country  |      Date    | Image | URL to link from Image|
|----------|:-------------:|--------:|:------|
|Accra, Ghana | May 2018 |![AccraOpenAQ_GroupPhoto](https://user-images.githubusercontent.com/13404290/64055983-41093e80-cb5e-11e9-9d2b-614b90743eab.png)| https://www.dropbox.com/s/mksfchtt9ju7h2m/Public_Sub-Saharan%20Africa%20Workshop%20Report.pdf?dl=0 |
|Delhi, India | November 2016 |![Delhi_OpenAQ_2016_GroupPhoto](https://user-images.githubusercontent.com/13404290/64055957-0ef7dc80-cb5e-11e9-833a-b33d8e49ab5d.JPG)| https://medium.com/@openaq/delhi-openaq-workshop-info-materials-and-results-2bd74b88bee6 |
|Sarajevo, Bosnia |February 2017 | ![Sarajevo](https://user-images.githubusercontent.com/13404290/64055978-39499a00-cb5e-11e9-9b4f-31c7050ab078.JPG)|https://www.dropbox.com/s/436sug0dubutfu6/Report%20from%20the%20Sarajevo%20OpenAQ%20Workshop.pdf?dl=0 |
|Nairobi, Kenya | May 2018 | ![nairobi](https://user-images.githubusercontent.com/13404290/64055953-03a4b100-cb5e-11e9-838d-092246e8553d.png)| https://www.dropbox.com/s/mksfchtt9ju7h2m/Public_Sub-Saharan%20Africa%20Workshop%20Report.pdf?dl=0  |
|Pristina, Kosovo| June 2019 |![kosovo](https://user-images.githubusercontent.com/13404290/64055968-2767f700-cb5e-11e9-8696-f1b3db21569b.png)|https://www.dropbox.com/s/kxvx9fq7oq5bjxh/Kosovo_Public_AQOpenData_Workshop2019_Memo.pdf?dl=0|
|Ulaanbaatar, Mongolia| November 2015 | ![UB_OpenAQ](https://user-images.githubusercontent.com/13404290/64053544-d998c200-cb50-11e9-8510-be6facc66a4b.JPG) | https://medium.com/@openaq/the-ub-openaq-workshop-results-5e9a9829660c |

**Comment by olafveerman** [comment]
@RocketD0g Do you have the Accra and Nairobi pictures without text?

**Comment by RocketD0g** [comment]
@olafveerman I actually don't, not readily. If I can find them, I will add them later. I know this makes them look different than the others...

**Comment by olafveerman** [comment]
Content added. Closing this issue.
