### ISSUE TITLE
Review buttons size

### ISSUE THREAD

**Issue by ricardoduplos** [openaq/openaq.org#324]
Enlarge buttons throughout the site. Apply `button--xlarge` modifier.

Example of button that needs to be bigger:

![Screen Shot 2019-09-03 at 12 02 12](https://user-images.githubusercontent.com/1016701/64168281-17446600-ce43-11e9-951b-1f4e59e77abf.png)

**Comment by jflasher** [comment]
Closing this due to age, but can be reopened if community continues to raise as an issue.
