### ISSUE TITLE
Issue seeing new data sources added to system

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq.org#346]
I just went to add in a few new data sources (e.g. Kabul, Afghanistan, Guatemala City, Guatemala), and I can see these locations on the map, but not on the "country" page, for example.

It looks like the Athena command is no longer running to update the locations?

cc: @jflasher @vgeorge 

PS> Possibly also associated with behavior observed in: #345?

**Comment by jflasher** [comment]
Just looked and the queries are not being run on Athena, even though the normal one is. I feel like this is odd since both of these queries are supposed to be started at the same time.

**Comment by jflasher** [comment]
Looked into this more and I think the only place this can fail if we're not seeing queries being run on Athena is at https://github.com/openaq/openaq-api/blob/develop/api/services/athena-sync.js#L284. I restarted all the EC2 instances running the API and the Athena queries are running again. This makes me think that somehow `updating` is getting stuck as `true`. @vgeorge any idea how that'd happen? I thought `finally` would be run even if there was an error in the execution?

**Comment by vgeorge** [comment]
@jflasher I've mocked an execution error in the function you pointed and `finally` is executed properly. I believe there are two possible causes for this problem: (1) a query keeps running without raising a timeout error, which blocks running `finally`, or (2) a query has an error that kills the server proccess, which keeps restarting without finishing the sync. I would have to look at the server logs, but I believe I don't have it yet. Can you provide it?

**Comment by jflasher** [comment]
Unfortunately I don’t think there are any relevant server logs here. I didn’t see any king in the Athena history, the debug logs will be hard to see since they’re on ephemeral instances and Papertrail wouldn’t have this level of detail. I’m wonder if instead of the update var, do we do an iSActive check like https://github.com/openaq/openaq-api/blob/develop/api/controllers/webhooks.js#L74?
