### ISSUE TITLE
Wrong number of countries listed on website

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq.org#353]
Currently, we list that there are 91 countries in OpenAQ's system.

![Screen Shot 2019-11-04 at 6 28 45 PM](https://user-images.githubusercontent.com/13404290/68166681-1908d380-ff31-11e9-8ff6-5f660dd4b5fb.png)

But in reality, there are 8 fewer because these are appearing in our system as individual "countries":
![Screen Shot 2019-11-04 at 6 29 01 PM](https://user-images.githubusercontent.com/13404290/68166688-1c9c5a80-ff31-11e9-8ea5-668d68116826.png)

I believe the underlying issue is coming from a change in the AirNow data source in openaq-fetch BUT given I think this will be difficult solve at the source-level (@jflasher, tell me if you think I'm wrong or there is another way we could have this value dynamically and correctly update), I think it may be more expedient to make the number of countries reporting be a static number we must change manually. 

I realize manually updating is prone to being an under count of the countries in our system, but I think it'd be better to be under on the country count than over.

**Comment by dolugen** [comment]
Until the source country code issue is resolved, #380 should help.
