### ISSUE TITLE
map marker colors don't match legend

### ISSUE THREAD

**Issue by andrewharvey** [openaq/openaq.org#364]
![Screenshot from 2020-01-07 11-07-06](https://user-images.githubusercontent.com/117278/71858097-0cc21200-313e-11ea-8638-553b10f4dd34.png)

it looks like 0 values are using grey but 0.001 would use blue. I think it's better for 0 values to use the base colour as shown in the legend.

**Comment by jflasher** [comment]
Closing as I believe desired behavior is occurring. In this case, I believe the grey is because selected data point is old, not because it's 0.
