### ISSUE TITLE
Historical SO2 wrong units

### ISSUE THREAD

**Issue by ReaRuiRay** [openaq/openaq.org#365]
This historical SO2's unit should be ppb or ug/m3 instead of ppm, which is way too large. I think that is a bug in UI. Tagging @sruti 🥇 

https://openaq.org/#/location/%E6%B1%89%E5%8F%A3%E6%B1%9F%E6%BB%A9?parameter=so2&_k=730s6s

![image](https://user-images.githubusercontent.com/11169226/74117935-5e096980-4bf4-11ea-850e-18ed061f603c.png)

**Comment by jflasher** [comment]
Page has moved to https://openaq.org/#/location/9023 but confirmed this is now correctly showing µg/m³.
