### ISSUE TITLE
US data from Boston labelled as Portsmouth UK 

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq.org#406]
A community remember reports:

> I was checking Portsmouth UK data on your website ( https://openaq.org/#/location/Portsmouth?_k=xcood3 ) but after downloading data in csv format I realize they are mapped as Portsmouth US, so apparently there is a bug.
> 
> Do you know if :
> 
> - it's just a bug of label, meaning its Portsmouth UK data even if CSV files says it's Portsmouth US and I just have to change position manually
> - it's a bug of data and by clicking on download Portsmouth UK I download Portsmouth US

It's unclear to me why Boston data appears for Portsmouth, UK on the website, but it doesn't seem to be an issue with making the call via the API.

This does give back (as it should) both data from the UK and US): 
https://api.openaq.org/v1/locations?city=Portsmouth

**Comment by jflasher** [comment]
This should no longer be an issue as location names aren't used in URL structure.
