### ISSUE TITLE
Node locations map (mobile only)

### ISSUE THREAD

**Issue by jvntf** [openaq/openaq.org#422]
![image](https://user-images.githubusercontent.com/19439427/98034280-bf0d4900-1de4-11eb-88d5-452bdb2bd671.png)

What is the content of this? @rwegener2 cc @alicer

**Comment by rwegener2** [comment]
## Overview
This component is meant to show a map of the different point locations were taken within a single node.  This functionality is only relevant to mobile nodes so it should selectively render only on mobile locations dashboards.  It is meant to be similar to the [first main component](https://aqdatacommons.org/superset/dashboard/houston_mobile_municipal/) on the AQDC dashboards.

![Screen Shot 2020-11-25 at 7 32 12 AM](https://user-images.githubusercontent.com/35503632/100234420-adedbe80-2ef0-11eb-9e02-dd049a351f5d.png)

## Stages of Completion
The MVP of this component should render point locations across the map.  The v2 of this component will allow a user to select a pollutant and color the point locations based on the value of that pollutant.
