### ISSUE TITLE
remove the Total Count of Measurements from stationary locations & datasets dashboards

### ISSUE THREAD

**Issue by jvntf** [openaq/openaq.org#454]

**Comment by AliceR** [comment]
It looks like this is already done, @jvntf ? Can we close the issue?

**Comment by jvntf** [comment]
i dont think its done? 
![image](https://user-images.githubusercontent.com/19439427/103903703-3bb0f200-50ca-11eb-9e6f-0c8d2316544a.png)

**Comment by AliceR** [comment]
Ok nevermind then. I thought this referred to the dashboard map component with the same title. 
Why do we want this number removed though?

**Comment by jvntf** [comment]
Ah you are correct! But i don't see any conditional logic to remove a card...was that card just removed altogether?

**Comment by AliceR** [comment]
It was: https://github.com/openaq/openaq.org/commit/96318a444d5b9be418753989c4d75bea86e9b8ec - we will likely bring the actual component back with a different title and functionality at some point
