### ISSUE TITLE
Map rendering of data locations

### ISSUE THREAD

**Issue by rwegener2** [openaq/openaq.org#472]
## The Task
Currently no locations are rendering on [the world map](https://openaq-staging.org/#/map).

This map originally showed all of the OpenAQ sensor locations.  It should show those and also show all of the new locations that have been added as a part of the LCS project.

## Notes/Concerns
@bitner Do you foresee any backend concerns?

### Mobile Nodes
I believe that mobile nodes come back as a list of points.  Is there a way to render those as a single point for simplicity?  It seems like at most zoom levels this would be preferred.

## Updated Styling
We would like at some point for LCS sensors to render as squares and government sensors to render as circles, something like in this wireframe:
![Screen Shot 2020-12-13 at 8 33 02 PM](https://user-images.githubusercontent.com/35503632/102033956-6ab19d80-3d82-11eb-8c82-6bb6b7fb0fb2.png)

Devs should decide, however, if that is easier to do as a part of this ticket or a separate one.  The styling updates are currently documented in [this card](https://github.com/openaq/openaq.org/projects/1#card-50060787).

**Comment by AliceR** [comment]
https://github.com/openaq/openaq.org/pull/476 contributes to this ticket by updating the maps to use vector tiles which allows us to display _a lot more_ locations than with the previous approach of fetching and parsing locations from endpoint to display as geojson. We also added a layer for the mobile sensor bboxes.
We still would need to:
- scale the old visualization approach for more parameters (currently only a small set of parameters is handled in [utils/map-settings.js](https://github.com/openaq/openaq.org/blob/develop/app/assets/scripts/utils/map-settings.js)), all the new ones need to be included in the approach)
- differentiate the symbolization for lcs vs government
- filter the locations on the country page to only show those, as in the old version :
<img width="1502" alt="Screenshot 2020-12-21 at 20 00 53" src="https://user-images.githubusercontent.com/1732578/102812411-3f086600-43c7-11eb-8b79-29f75053a3f3.png">

**Comment by rwegener2** [comment]
I added the three tasks from @AliceR's comment as cards in the project board with references to this ticket.

**Comment by rwegener2** [comment]
One question to investigate on the above comment - After how long without no updates before a location on the existing world map turns grey?  OpenAQ didn't know off hand what this length of time is, but they said they wanted it to be roughly the same as the current world map functionality.  They thought this would be roughly a few days.  For the "confirm date functionality" task above we should determine how long this length of time is.
