### ISSUE TITLE
Locations and Dashboard Hub card consistency

### ISSUE THREAD

**Issue by rwegener2** [openaq/openaq.org#478]
In order to get some consistency across the search endpoints we would like to display as similar of information as possible on the Locations Hub cards as on the Datasets Hub cards.

### Each card should display, in the following order:
Collection Dates _start date_ - _end date_
Measurements _#_
Parameters (this is the new name for Pollutants/Measurands) _ex. NO2, CO_
Locations _#_ **the only field that is different - this should show up only on the dataset cards**
Sources (a string, or for a dataset this could be a list)

**Comment by jvntf** [comment]
projects objects do not contain a source list @rwegener2 @bitner

**Comment by rwegener2** [comment]
@jvntf Thanks for pointing this out.  Let's skip adding a source to the Datasets card for now.
