### ISSUE TITLE
Migrate to Github Actions

### ISSUE THREAD

**Issue by necoline** [openaq/openaq.org#503]
We have run into a number of issues with the speed, flexibility and testing integration options available with Travis CI.

It is possible that these issues are resolved with adjustments to our setup, but given that we have more experience with github actions and actions seem to be a superior CI experience generally, we would like to make that transition.

A few things that we would like github actions to do:
- runs lint and cypress tests a caches node modules when commits are pushed a branch 
- builds and deploys to staging when PR is made to develop

**Comment by AliceR** [comment]
For reference, there already is a Github action workflow in place to run lint and test jobs: https://github.com/openaq/openaq.org/blob/develop/.github/workflows/lint-and-test.yml
