### ISSUE TITLE
Locations Hub page - Filters updates

### ISSUE THREAD

**Issue by tania-pires** [openaq/openaq.org#535]
## Goal
The "Sensor Type" filter has gotten more detailed, so we would like to change the format of the filter dropdown so as not to clutter the filter lists.  This will involve adding new filters to the search.

## Details
The "Sensor Type" filter allows 3 distinct selections: Grade, Mobility, and Entity. 

### Grade
Low Cost Sensor or Reference-grade

**Example API Call**
`https://0jac6b9iac.execute-api.us-east-1.amazonaws.com/v2/locations/35840`
`results` -> `sources` -> `sensorType`

**Manufacturer Filter**
The Manufacturer type dropdown will be enabled only if Low Cost Sensor is chosen.

Implementation notes:
I see that if you know the name of a manufacturer you should are able to filter locations by it (Example https://0jac6b9iac.execute-api.us-east-1.amazonaws.com/v2/locations?manufacturerName=Picarro).  I don't see an endpoint to list the manufacturers, however.  @bitner would you please comment how many manufacturers there are across all the datasets?  Could we make an additional endpoint to enumerate the available options?

### Mobility 
Mobile or Stationary

**Example API Call**
`https://0jac6b9iac.execute-api.us-east-1.amazonaws.com/v2/locations/35840`
`results` -> `isMobile`
This can mirror the functionality of the existing mobility filter.

### Entity 
Community or Research or Government

**Example API Call**
`https://0jac6b9iac.execute-api.us-east-1.amazonaws.com/v2/locations/35840`
`results` -> `sources` -> `entity`

## Screenshots
<img width="861" alt="Screenshot 2021-01-08 at 15 20 25" src="https://user-images.githubusercontent.com/22524740/104031733-09d08600-51c5-11eb-8ce2-3fd9636214d7.png">

![Sensor type](https://user-images.githubusercontent.com/22524740/104031699-fa513d00-51c4-11eb-9b80-e3482f70454d.png)

## Notes
The screenshots say "Lcs" but we would like to be more explicit going forward, so let's type out "Low Cost Sensor" instead.

**Comment by rwegener2** [comment]
Following up from our morning meeting @bitner to add:
* location filter for entity type
* endpoint for filter by manufacturer name
