### ISSUE TITLE
Announcement banner on homepage

### ISSUE THREAD

**Issue by rwegener2** [openaq/openaq.org#537]
## Goal
OpenAQ would like to announce their exciting new data on their homepage.  We have wireframes for what that could look like [here](https://projects.invisionapp.com/share/EZZGACI7CPD#/screens/441697018_1-_Homepage_Banner).

## Details
Of the two links the "Explore the data" one should link to the locations page and the "read our blog post" one should just be empty for now.  We can add the link when OpenAQ has it written.

**Comment by rwegener2** [comment]
Feedback:
> Homepage Banner design from Tania looks great! Is it possible to move it below the white navigation menu and make the bar and text a bit bigger?

**Comment by tania-pires** [comment]
To bar redesign according to feedback: 
![OpenAq-Top bar notification](https://user-images.githubusercontent.com/22524740/104188515-42fd3600-5411-11eb-9989-d33be76f244b.png)
