### ISSUE TITLE
Countries Hub updates

### ISSUE THREAD

**Issue by rwegener2** [openaq/openaq.org#543]
## Goal
Walk through the countries hub and make sure that the existing OpenAQ functionality is in alignment with our updates and the presence of LCS data.

## Details
Checkboxes are things to check on.  Quotes below come from the feedback documents.

- [x] ~Investigate what is meant by number of locations~ There is only one definition of a location, the one we have been using throughout this project.  So the number of locations number is incorrect.

Ex. Germany & Canada have lots more locations on their respective pages than are listed on the card; Costa Rica doesn't seem to have any even though the card says 1.
> Australia lists 13 but there are many more on the country page.
- [x] Investigate why nothing shows up next to measurements (countries cards and countries page headers)
- [ ] Some of the countries are missing (Ex. Andorra, Bahrain, Bermuda)

### Nice to Have
- [x] Scrolling
> When scrolling through the country pages, the mouse gets stuck on the map that zooms in and out. Is there a way to fix this so that it’s easier to scroll through the page?

**Comment by AliceR** [comment]
> Investigate why nothing shows up next to measurements

We need to add the measurement count to the /v2/countries/:id response, added a card [here](https://github.com/openaq/openaq.org/projects/1#card-52733552) (cc @bitner)

**Comment by AliceR** [comment]
> the number of locations number is incorrect.

the number displayed is provided with the /v2/countries/:id response as `locations`

**Comment by AliceR** [comment]
While investigating the above, I noticed that the label `areas` never shows a number - it is currently set up to display what is provided with the /v2/countries/:id response as `cities`, but I could not find an example where this exists.

For the number of sources, we currently iterate over the locations cards and find unique values. I think it would be better to include that to the endpoint.

**Comment by AliceR** [comment]
> Some of the countries are missing (Ex. Andorra, Bahrain, Bermuda)

Those are not provided with /v2/countries

**Comment by rwegener2** [comment]
Also:
add number of sources to /v2/countries objects

**Comment by rwegener2** [comment]
What you said about areas returning cities makes sense @AliceR I think we should remove the `areas` number because the majority of the data now does not have a city, or at least not a valid one

**Comment by rwegener2** [comment]
### Frontend actions
All of the backend issues raised here have been addressed, with just one left in progress (A few missing countries, see note below).  That leaves the following frontend tasks re-open for development:
* updates sources to use the endpoint directly instead of iterating
* remove areas from the countries page

### Extra background
Outcome of the missing countries problem:
* some have gotten readded because they were removed by mistake.  Others were the result of a data mismatch and that problem will be addressed soon.

Countries that are still not displaying correctly: Bosnia, Sri Lanka, Costa Rica, Iraq, Kuwait, Sudan, Tajikistan, Turkmenistan, Vietnam

cc @AliceR

**Comment by AliceR** [comment]
> remove areas from the countries page

✔︎ https://github.com/openaq/openaq.org/pull/601

**Comment by AliceR** [comment]
> updates sources to use the endpoint directly instead of iterating


✔︎https://github.com/openaq/openaq.org/pull/609

**Comment by rwegener2** [comment]
Everything in this ticket is complete with the exception of the data mismatch from using/not using ISO standard names.  This issue affects: Bosnia, Sri Lanka, Costa Rica, Iraq, Kuwait, Sudan, Tajikistan, Turkmenistan, Vietnam.  

There is no movement to fix this so I am closing this ticket.
