### ISSUE TITLE
Additional filters to dataset search

### ISSUE THREAD

**Issue by jvntf** [openaq/openaq.org#572]
## Goal
We would like to add the following filters to the datasets search:
* Sensor Type filter
* add Data Source filter

## Details
I think this is possible using the `/projects` endpoint.  The data source and sensor type filters should look like those same filters on the [locations page](https://openaq.org/#/locations).  The difference with datasets is that the projects are tagged with a list instead of a single string so we should return results if they include that item in their list.

~For example, a dataset with the tags 'community' and 'government' would get returned if these entities were chosen:~
* ~just community~
* ~government entity~
* ~both community & government~

~It would not get returned if:~
* ~just research~
* ~both research & community~
* ~both research & government~
* ~all three research, community & government~

### Update 
I made a mistake - each dataset gets assigned one value of the predominant sensor Type.  I think this filter should just work like the locations, in that case, returning all of the locations that match the selected value.

It's worth noting that right now none of these complex scenarios exist because none of our current datasets should have multiple tags.

**Comment by jvntf** [comment]
note that tags on dataset is blocked by backend changes

**Comment by rwegener2** [comment]
I moved the entity tag to a locations card to a separate project card.  This ticket is morphing to represent all of the changes that we might make to the datasets page, but we are waiting on partner input.
