### ISSUE TITLE
Dashboards - Single date selection only shows up on refresh

### ISSUE THREAD

**Issue by jvntf** [openaq/openaq.org#575]

**Comment by jvntf** [comment]
not able to replicate, can you provide example / info please @rwegener2

**Comment by rwegener2** [comment]
This issue happens to me only the first time I navigate to a locations page.  When I go through and click the buttons to select a date the url changes to include the date range but the graph looks like this:
<img width="1147" alt="Screen Shot 2021-01-13 at 8 25 27 PM" src="https://user-images.githubusercontent.com/35503632/104536314-7b516f80-55dd-11eb-9f0c-591e9c5ae921.png">
If I refresh that URL or navigate directly to it the graph shows up fine.  After the refresh to get it to show up I can change the date and new sets of points render as I choose new dates, like I would expect them to.
#### Example:
* https://openaq-staging.org/#/location/35644?dateRange=2021/1/10
