### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq.org#59]
Don't know where we want to put this, but since a q came up:

**OpenAQ Privacy Policy**
We do not store any personal information. We use Google Analytics to help analyze how visitors use this site. Google Analytics uses “cookies” to collect standard internet log information and visitor behavior information in an anonymous form.

**Comment by masalmon** [comment]
Cool -- we also need a specific text for the API. :smiley_cat:

**Comment by jflasher** [comment]
@sruti this is likely still relevant to have included somewhere, perhaps the FAQ?

**Comment by maelle** [comment]
For info for rOpenSci website we started using Matomo Analytics (more ethical, but not free).
