### ISSUE TITLE
sources not displayed on projects card (projects hub)

### ISSUE THREAD

**Issue by jvntf** [openaq/openaq.org#591]

**Comment by jvntf** [comment]
sources inside of project object is an array of arrays instead of array of object 
![image](https://user-images.githubusercontent.com/19439427/104773604-4fe89500-5743-11eb-95c7-38471f6fdd1a.png)

**Comment by rwegener2** [comment]
> fixed on new staging https://b4qc1cqcm2.execute-api.us-east-1.amazonaws.com/v2/projects

From Bitnerd
