### ISSUE TITLE
Nearby Locations updates

### ISSUE THREAD

**Issue by rwegener2** [openaq/openaq.org#613]
## Goal
Revisit the Nearby Locations component and document anything that should be changed with the expanded dataset

### Displaying non-Core parameters
* map defaults to a non-Core parameter so it has a NaN legend

Example: http://localhost:3000/#/location/6178

I wonder how hard it would be to continue to show non-Core parameters but just remove the color scale.  This might involve a little refactoring to consider how a user would switch between core and non-core parameters.  This is a bit of extra logic but if we try to remove non-Core parameters from the map completely we'd still need to figure out what to do with the map with a location doesn't report any non-Core parameters.

### Location dot doesn't appear
Example: https://openaq-staging.org/#/location/5650, https://openaq-staging.org/#/location/10915

**Comment by necoline** [comment]
I think this must have been updated on the api, because I cannot reproduce the missing location dot on the listed locations ☝️
