### ISSUE TITLE
Location cards - replace 'In `city`, `country_code` with location ID

### ISSUE THREAD

**Issue by rwegener2** [openaq/openaq.org#632]
## Goal
Since there are so few sensors that have a city name we are removing them from the results cards and replacing them with ID to distinguish them from other cards in the event where a cards doesn't even have a location name.

## Details
Page: https://openaq-staging.org/#/locations
Where the following card says "in No listed city, GR" ~remove~ above that ~and~ write "Location ID 62216".  This will result in 3 lines of information on the top of the card.
![Screen Shot 2021-01-20 at 7 45 42 AM](https://user-images.githubusercontent.com/35503632/105183188-803d8400-5af3-11eb-99d9-519151474275.png)
To keep the country code let's add COUNTRY CODE in the grey writing below between Measurements and Parameters.

**Comment by rwegener2** [comment]
### Update from OpenAQ Meeting
We want to keep the "in city name, country code" line in the top of the card, but just add the location ID line above it

**Comment by jvntf** [comment]
just in time
