### ISSUE TITLE
Unit rounding

### ISSUE THREAD

**Issue by rwegener2** [openaq/openaq.org#669]
## Goal
The Latest Measurements component at the top can look a little sloppy (and convey undue certainty) when very large numbers are rounded to several decimal places.  

Instead lets show:
* any number with a ~value > 2~ value < 2: round to two decimal places
* any number with a value >= 2: round to the nearest whole number

## Details
These changes will be relevant on both the projects dashboards (Ex. Houston Mobile https://openaq-staging.org/#/project/28974) and the locations dashboards (Ex. https://openaq-staging.org/#/location/61507)

## Additional
This is most important in the Latest Measurements component, but if possible this should apply to all numbers on the site.  This includes:
* time series hover text on dashboards
* parameters table values
* latest reading in the map popups

**Comment by jvntf** [comment]
@rwegener2 should this be < 2 and >=2

**Comment by rwegener2** [comment]
@jvntf yes 100%, thanks for catching
