### ISSUE TITLE
Text updates

### ISSUE THREAD

**Issue by rwegener2** [openaq/openaq.org#670]
### Dataset dashboards: new info button

Add an info button after "Values for all stations" that says:
> The data shown below is an average across all the locations in this dataset

For the stationary datasets pages (with node selection) I think we should add a new header that says "Values for selected stations" that appears after the grey component when the map is in the "Select locations" mode.  The info text next to that one would be:
> The data shown below is an average across all the selected locations

I might have missed something in this, though, so comment with other ideas if folks have them.
### temporal coverage hover text clarification (datasets page only)

Add an additional line that says: 
> If a parameter is not present at one location in the dataset it will be omitted from the average.

If this line could come between the two existing sentences (become the second sentence) that would be great.

> The avg # for each pollutant by hour, month. **New sentence** In some views ...

**Comment by rwegener2** [comment]
(Adding a third thing)
### temporal coverage labels
* change the y axis label from "count" to "avg count"
* make x axis label on the Hour of Day chart Hour instead of Date
* Hour of Day x axis - reverse the order (left side is hour 0 instead of hour 24) and write out the ":00" part to clarify that we are talking about the hour of the day.  So from left to right the x axis would show: 1:00, 3:00, 5:00, 7:00, and so on.

**Comment by AliceR** [comment]
Just noting, the analysis dashboards actually do not contain any average values anymore. 
<img width="1202" alt="Screenshot 2021-01-26 at 13 29 49" src="https://user-images.githubusercontent.com/1732578/105845127-9313f500-5fda-11eb-85de-9aa82a1a07e0.png">

**Comment by AliceR** [comment]
> make x axis label on the Hour of Day chart Hour instead of Date

I think we better omit the additional label below the x axis, it seems to me that the title says it all. It would look like this:

<img width="1154" alt="Screenshot 2021-01-26 at 13 54 36" src="https://user-images.githubusercontent.com/1732578/105847561-09662680-5fde-11eb-9cd1-4596a91e3346.png">

<img width="1149" alt="Screenshot 2021-01-26 at 13 52 14" src="https://user-images.githubusercontent.com/1732578/105847291-b42a1500-5fdd-11eb-9923-209ec237d41f.png">

**Comment by rwegener2** [comment]
Reopening this ticket with a few new items:

**Dashboard: Temporal Coverage**
- [ ] show the x axis values in increasing order (hour of day shows 1:00 on the left side, then 3:00 and so on.  Day of week starts with Monday on left, then Tuesday and so on.  Year starts with January on the left.

**Mobile Dashboard pages**
- [ ] "Values for all __ stations": remove the word "all" and change the word "stations" to "nodes"

**Comment by rwegener2** [comment]
Closing this and moving the most recent tasks to their own issue.  The reopened one was confusing even me, and I was the one that made the change 😶 

https://github.com/openaq/openaq.org/issues/692
