### ISSUE TITLE
Time series daily project lifetime

### ISSUE THREAD

**Issue by rwegener2** [openaq/openaq.org#678]
## Goal
Provide a higher data resolution to the users on the default view of the dashboard page.

## Details 
Time series component:
We would like to show the hourly average of all the data across the entire lifetime of the dataset.  Right now I think by default it might show the latest week

**Comment by necoline** [comment]
I thought this was our plan so as to reduce expensive calculations. Maybe I'm remembering this wrong
cc: @bitner

**Comment by rwegener2** [comment]
@necoline David and I chatted about this yesterday.  We are keeping the binning at daily, which means that even two years of daily data is 730 points.

I am a little concerned about crashing if a sensor has years and years of data, so we could add a two year max to this.
