### ISSUE TITLE
sporadic downloads woes

### ISSUE THREAD

**Issue by rwegener2** [openaq/openaq.org#683]
(Work in progress ticket)
### other mystery issue
From a location dashboard page like this: https://openaq-staging.org/#/location/36412

With download selections like this:
Country - US
City - OXFORD
Location - Ramford
Start date - 2021 Jan 4
End date - 2021 Jan 20

Returns this

https://b4qc1cqcm2.execute-api.us-east-1.amazonaws.com/v2/measurements?format=csv&limit=66536&location=36412&date_from=2021-01-03T23%3A00%3A00.000Z&date_to=2021-01-19T23%3A00%3A00.000Z

From dataset cards, download button on both Mesa Methane card and Mesa Methane dataset dashboard page, leave all download selections as default, returns this:  https://b4qc1cqcm2.execute-api.us-east-1.amazonaws.com/v2/measurements?format=csv&limit=66536&project=28958

 Both these return []

**Comment by AliceR** [comment]
Mystery issue: 
https://b4qc1cqcm2.execute-api.us-east-1.amazonaws.com/v2/measurements?format=csv&limit=66536&location=36412&date_from=2020-12-31T23%3A00%3A00.000Z&date_to=2021-01-12T23%3A00%3A00.000Z
Start date in December with end date in January gives back results across January. Both start date and end date in January return [].

**Comment by rwegener2** [comment]
The first issue we couldn't reproduce so we've. reached out asking or more specific details. 

The second issue has been investigated by @aliceR and resolved on the API side by @bitner.
