### ISSUE TITLE
General Improvements

### ISSUE THREAD

**Issue by necoline** [openaq/openaq.org#708]
In addition to work mentioned [here](https://github.com/developmentseed/team-impact/issues/82)

Additional improvements could include

### Resiliency
- increase test coverage
- improve flaky tests

### General Improvements
- remove unnecessary redux, replace with local state and hooks, wrap with console logging
- clean out dead code
- Reduce repetition between project hub / locations hub pages
- Styled component usage / reduce dispersion of styles between design system, SCs, local sass

### Maintainance
- docs on how to use the design system, getting started as a developer, making contributions
- clean out old issues (ones that have been around for over a year)
- document issues that are easy to pick up by contributors

**Comment by AliceR** [comment]
Thanks @necoline , I updated you list with my suggestions

**Comment by jvntf** [comment]
@necoline added mine as well
