### ISSUE TITLE
world map - displaying parameters with different units

### ISSUE THREAD

**Issue by rwegener2** [openaq/openaq.org#720]
## Overview
In the old openaq.org website we think that there were more locations that were displayed on the world map because for some parameters the map was displaying parameters with different units together.  We would like to get more locations to show up on the map again, but the details of how need investigation.

## Details
In our new backend system pollutants with different units are considered to be completely unique.  For the purposes of the map, however, we still want both units of measurement to show up as though they were the same parameter.  It isn't clear if previously the non-standard units were all showing up grey, if they had a unique color scale, or something else.

### Parameters
In the table we have listed the "Displayed Parameter" which is the parameter that is currently being displayed in the world map.  The "Add Parameter" is the one that we would like to add to the world map together with the Displayed Parameter.
|  displayed parameter (ID) | add parameter (ID) | conversion |
|---|---|---|
| CO (8) | CO mass (4)  | 0.000904379 | 
|  NO2 (7) | NO2 mass (5)  | 0.000550492 | 
|  O3 (10) |  O3 mass (3) | 0.000395666 |
|  SO2 (9)| SO2 mass (6)  | 0.000527554 |

The name of the parameter on the legend does not have to change.

## Tasks
* Task 1 of this ticket is to do a preliminary look to see if we can tell what was previously happening with the map.  This should be time capped, though, to maybe 30-45 minutes so as to not go down a rabbit hole.
* Task 2 will be to implement adding locations the non-standard units as either greyed out points or set up a system giving them their own color scale.

Between tasks 1 and 2 we will need to consult OpenAQ to see how they want to proceed in task 2.

**Comment by AliceR** [comment]
The old version (https://github.com/openaq/openaq.org/commit/e53db43e2c204594ad00873b7b0e494625ed1694) requests [large amounts of data from the /latest endpoint](https://github.com/openaq/openaq.org/blob/e53db43e2c204594ad00873b7b0e494625ed1694/app/assets/scripts/actions/latest-measurements.js#L47), parses that [data into geojson features](https://github.com/openaq/openaq.org/blob/e53db43e2c204594ad00873b7b0e494625ed1694/app/assets/scripts/components/map.js#L272) and [converts measurement values](https://github.com/openaq/openaq.org/blob/e53db43e2c204594ad00873b7b0e494625ed1694/app/assets/scripts/utils/map-settings.js#L69). This left the user with a blue loading screen for quite some time until all data was loaded, and further makes up ~8MB of resources to load. 

The new version using the api v2 just gets the [data from vector tiles](https://github.com/openaq/openaq.org/blob/develop/app/assets/scripts/components/map/locations-source.js#L18) and [displays it based on its properties](https://github.com/openaq/openaq.org/blob/develop/app/assets/scripts/components/map/measurements-layer.js#L52), making the whole experience significantly faster and and technically scalable with more and more data to add. Vector tiles are optimized to handle large amounts of data.

To get more data displayed on the map, I can think of these approaches:

  a) we update how the backend generates the vector tiles to merge and convert locations measuring the same parameter in different units, providing the property in that unit that is supposed to be displayed with the legend. For this approach, no changes on the frontend are needed.

  b) we add an additional layer to the world map that shows _all_ available locations regardless of the parameter they are measuring in a neutral color. This could be the same grey as the outdated locations. We can update the explanation in the legend to indicate that we show outdated locations as well as locations that do not measure the selected parameter in grey.
  
cc @rwegener2 @bitner @sruti

**Comment by sruti** [comment]
After getting some historical perspective, we think it's okay to convert the units for display purposes (similar to how it [was done before](https://github.com/openaq/openaq.org/blob/db272d62a87810875613a9b0bd0e0edd15d49bab/app/assets/scripts/utils/map-settings.js) using [STP](https://www.engineeringtoolbox.com/stp-standard-ntp-normal-air-d_772.html)) but we absolutely can not modify how we store data in the DB and serve it through the API

**Comment by AliceR** [comment]
It was decided to load the [measurements as separate api requests and layers](https://github.com/openaq/openaq.org/blob/develop/app/assets/scripts/views/world-map.js#L90) to the world map, while making sure that the color representation still matches. The color scheme is defined using a max color value which is considered the upper value of the range, and [linearly interpolates](https://github.com/openaq/openaq.org/blob/develop/app/assets/scripts/utils/colors.js#L116) between [0 and that max value](https://github.com/openaq/openaq.org/blob/develop/app/assets/scripts/utils/colors.js#L79). By converting the max color value of one unit to the other unit, we can display both units using the same coloring, even though the underlying values are provided in different units.
