### ISSUE TITLE
Performance Benchmarking

### ISSUE THREAD

**Issue by jvntf** [openaq/openaq.org#728]
Ticket outlining approach / discussion regarding benchmarks pre and post LCS work phase.

Notes to be formalized into markdown files / ADR

cc @necoline @AliceR

**Comment by jvntf** [comment]
#Lighthouse
Lighthouse provides performance audits for a web page. Includes performance, accessibility, best practices, seo ratings.

Lighthouse can be run by cypress, see [demo](https://github.com/mdcruz/cypress-lighthouse-demo). 
I suggest instead that we run lighthouse as a github action workflow on merge to develop / main. see [repo](https://github.com/GoogleChrome/lighthouse-ci).

IMO this would be a better developer experience, because of the integration of the rich text reports into github.


#[Pa11y](https://github.com/pa11y/pa11y)
Accessibility metrics. Lighthouse seems to have this covered. We can again add this from cypress, or use github actions. I recommend the latter. I don't think we really need this on top of Lighthouse unless there is something super specific someone wants to test.


#[Puppeteer](https://addyosmani.com/blog/puppeteer-recipes/)
Puppeteer does roughly the same things through lighthouse. Perhaps it has a more straightforward api for writing testing recipes? [Lighthouse CLI](https://github.com/GoogleChrome/lighthouse-ci) provides more or less the same features

**Comment by necoline** [comment]
I think lighthouse in through github actions sounds ideal

I don't think we have written any a11y cypress tests that go beyond what lighthouse checks for, but I may be mistaken on that. If we want to add more checks in the future, we can always add them to cypress

**Comment by AliceR** [comment]
We actually do not have cypress a11y checks in place for this project, as it would be a lot of work and changes to the codebase the get them pass. A lighthouse a11y score is the better approach for now, to get on the track towards improving.

I agree to setting up as github actions 👍
