### ISSUE TITLE
Mockup vs API review

### ISSUE THREAD

**Issue by olafveerman** [openaq/openaq.org#73]
Check the API coverage for the mockups

**Comment by olafveerman** [comment]
# Homepage
https://marvelapp.com/1e21bb3#13388532 

Most important findings for homepage:

- the OpenAQ's data section requires calls to 4 different endpoints
- the Compare Locations will involve quite some processing (pagination, filtering on date, etc)

## OpenAQ's data
The four stats in this section are available through 4 separate endpoints:

1. # locations - https://api.openaq.org/v1/locations
2. # measurements - https://api.openaq.org/v1/measurements
3. # countries - https://api.openaq.org/v1/countries
4. # sources - https://api.openaq.org/v1/sources

The response always follows the same structure:

**Response**:
```json
{
  "meta": {
    "found": 2555
  }
}
```

## Compare locations
The data for the chart comes from the [measurements endpoint](https://docs.openaq.org/#api-Measurements).
The response is paginated, with a default `limit` of 100, and a max `limit` of a 1000 results. A 100 results should be good for 24 hours of measurements with a 15 minute interval. A weekly chart with that reporting interval will require a little more than 1000 measurements.

Things to note:

- this may require pagination, depending on the reporting interval
- the endpoint contains all the meta information for the chart, except for proper country name (it returns the ISO code)
- it is possible to request data for a specific time-frame, but the date parameter filters the result on `utc` time, not on `local` time

Example:
https://api.openaq.org/v1/measurements?parameter=pm25&location=Bukhiin%20urguu&limit=100&date_from=2016-07-04T00:00:00&date_to=2016-07-11T00:00:00

## Recommended for you
All the information can be fetched using the [locations endpoint](https://docs.openaq.org/#api-Locations), specifying a set of coordinates and max radius in meters.

Example:
https://api.openaq.org/v1/locations?coordinates=52.3723,4.8792&radius=2000

**Comment by olafveerman** [comment]
# Locations page
https://marvelapp.com/1e21bb3#13386008

## Download data button
Comes from the [measurements endpoint](https://docs.openaq.org/#api-Measurements).

## Locations sections
The country filter can be constructed using the [countries endpoint](https://docs.openaq.org/#api-Countries) 
The data for the results can be fetched from the [locations endpoint](https://docs.openaq.org/#api-Locations)


Notes:

- it is not possible to specify multiple `parameters` and `countries`, which we need for the filters
- there is no endpoint that provides all the parameters in the system
- the # cities would have to be calculated client-side, loading all the data. I'd suggest we drop this.

**Comment by olafveerman** [comment]
# Map
https://marvelapp.com/1e21bb3#13414770

The map data can be fetched using the [latest endpoint](https://docs.openaq.org/#api-Latest), passing the `has_geo` parameter.

Example: https://api.openaq.org/v1/latest?has_geo

Two endpoints are necessary for the `other locations` functionality in the popup:

1.[ locations endpoint](https://docs.openaq.org/#api-Locations) passing coordinates + radius to determine locations in proximity
2. [latest endpoint](https://docs.openaq.org/#api-Latest) for the values of those locations

**Comment by jflasher** [comment]
@olafveerman to your point about # of cities on Locations page above, does https://api.openaq.org/v1/cities get you what you need?
