### ISSUE TITLE
mobile landscape margins

### ISSUE THREAD

**Issue by majesticio** [openaq/openaq.org#807]
Landscape view from mobile has the alignment off, with blank space on the right and the footer floating out. 

![Screenshot_20230113-160756](https://user-images.githubusercontent.com/67290377/212436391-3cc3be75-ec0f-4eb9-82ce-826e0b5873ae.png)
The wide margin on the right side is site wide in landscape view.  

![Screenshot_20230113-160729](https://user-images.githubusercontent.com/67290377/212436304-d5cf4888-97e5-4f8d-9877-1f27bcea3242.png)

Also no margin for text on the left.  
![Screenshot_20230113-161025](https://user-images.githubusercontent.com/67290377/212436490-6cb06182-c316-4138-aff5-295e43ba391b.png)

**Comment by russbiggs** [comment]
what size device is this on?

**Comment by majesticio** [comment]
resolution: 3040 x 1440 pixels
6.3 inches
