### ISSUE TITLE
Home page margins

### ISSUE THREAD

**Issue by majesticio** [openaq/openaq.org#809]
In mobile portrait view, no margins for text on the left, and the data example card is barely visible.
![Screenshot_20230113-160945](https://user-images.githubusercontent.com/67290377/212437332-ea1453a2-b5c6-49f4-b6cc-e8622f53378c.png)
In landscape view, same but with white space on the right side.  
![Screenshot_20230113-161025](https://user-images.githubusercontent.com/67290377/212437434-e39c05bd-fe2a-4a84-b243-e13e0f68881f.png)

**Comment by russbiggs** [comment]
resolved
