### ISSUE TITLE
Initiatives cards in mobile 

### ISSUE THREAD

**Issue by majesticio** [openaq/openaq.org#811]
Portrait view has the pictures to the side, could be better if the pic stacked on top of the description.  
![Screenshot_20230113-161243](https://user-images.githubusercontent.com/67290377/212437822-3e337bea-94f9-40c4-9266-75107c0c5434.png)

**Comment by russbiggs** [comment]
is this still an issue? if not let's close

**Comment by majesticio** [comment]
It is only aesthetic. Has not changed, but if preferred the way it is can close issue

**Comment by majesticio** [comment]
Will do.
