### ISSUE TITLE
Help page margins/placement for mobile

### ISSUE THREAD

**Issue by majesticio** [openaq/openaq.org#814]
Help page is misaligned in portrait view, cannot scroll left to read the content properly
<img width="428" alt="Screenshot 2023-01-19 at 9 54 41 AM" src="https://user-images.githubusercontent.com/67290377/213509065-b28b28ee-6443-4fd9-8440-e12fc5b9f407.png">

**Comment by majesticio** [comment]
the footer is fine

**Comment by russbiggs** [comment]
resolved in 85ebc1f752ef59da0721240b9461b35623af61d3
