### ISSUE TITLE
Location selector

### ISSUE THREAD

**Issue by danielfdsilva** [openaq/openaq.org#88]
![location-selector](https://cloud.githubusercontent.com/assets/1090606/17820970/3a625708-6647-11e6-94ef-3d3f239da4c4.png)

At the moment the location selector is being filled using data from the location api, so we have to download all the locations for a specific country. This is not really a scalable solution and something else should be thought of.

**Comment by jflasher** [comment]
This looks to still be the current behavior, but is performing better. Closing due to age and that it is possibly no longer an issue, community can reopen if it's still an issue.
