### ISSUE TITLE
Style : Add a scroll bar

### ISSUE THREAD

**Issue by SaranshBangar** [openaq/openaq.org#907]
Adding a personalised scroll bar (preferably of purple color) will look great!

![image](https://github.com/openaq/openaq.org/assets/114401238/c3379fa6-c7c5-4604-a9c8-15837893b9ba)

**Comment by russbiggs** [comment]
Thanks for this suggestion. Scroll bar styling is not very well supported across all browsers: https://caniuse.com/?search=scrollbar-color 
For this reason, and for following a our pre-determined style guide we will stay with the browser and OS default styles.

**Comment by SaranshBangar** [comment]
Understod sir, thank you so much for taking your time out to explain my mistake, I will make sure that this kind of silly problems do not arise again in my issues

**Comment by russbiggs** [comment]
Not a silly problem at all. Thanks for raising the suggestion, until today I didn't know the scrollbar was style-able, so I learned something new!
