### ISSUE TITLE
Contact form footer spacing bugs on Chrome

### ISSUE THREAD

**Issue by clairenied** [openaq/openaq.org#972]
Hello! I have noticed that the footer contact form on Chrome has some inconsistent margins and side-scroll behavior. Sometimes it also gets cut off! Images below: 

![Screenshot 2024-09-10 at 12 33 52 PM](https://github.com/user-attachments/assets/9db6614e-8287-4cac-aec6-71670992394f)
![Screenshot 2024-09-10 at 12 33 48 PM](https://github.com/user-attachments/assets/53a2818e-3b09-452e-b106-1a1d643810eb)
![Screenshot 2024-09-10 at 12 33 39 PM](https://github.com/user-attachments/assets/4345862d-3278-4545-83a3-8b5e02ca4638)
![Screenshot 2024-09-10 at 12 33 30 PM](https://github.com/user-attachments/assets/4547561d-156b-48a2-90c5-532eef307ba2)

I am happy to take a peek at debugging this, if it's ok with you.

**Comment by clairenied** [comment]
Hey! I just finished a local PR that fixes this, but it looks like I don't have access to push up a branch. Let me know if you are ok granting me permissions!

**Comment by russbiggs** [comment]
A fix for this would be greatly appreciated. I recommend forking the repo and submitting a PR from that.

**Comment by clairenied** [comment]
Oh my gosh of course I can do the fork thing: https://github.com/openaq/openaq.org/pull/973
